### ISSUE TITLE
v2 Release dependency issue

### ISSUE THREAD

**Issue by mantzas** [cloudevents/sdk-go#531] opened 2020-06-05 06:08 UTC
After upgrading to the new v2.0.0 release the following error occurs.

go: github.com/cloudevents/sdk-go/v2/protocol/kafka_sarama@v1.0.0-RC5 requires
        github.com/cloudevents/sdk-go/v2@v2.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

**Comment by adrianliechti** [comment] 2020-06-11 21:26
the same seems to apply to the stan protocol :/

**Comment by reachlakstar** [comment] 2020-06-21 02:26
This worked for me 
	github.com/cloudevents/sdk-go/protocol/pubsub/v2 master
	github.com/cloudevents/sdk-go/v2 master

(or) 
	github.com/cloudevents/sdk-go/protocol/pubsub/v2 v2.0.1-0.20200616162840-e7472fb4c849
	github.com/cloudevents/sdk-go/v2 v2.0.1-0.20200616162840-e7472fb4c849

**Comment by n3wscott** [comment] 2020-06-22 16:40
Yes, this was a mistake in the 2.0.0 release, next release we do will not have this issue, it is an ordering problem. Re: https://github.com/cloudevents/sdk-go/issues/525

**Comment by n3wscott** [comment] 2020-06-22 16:41
dupe of https://github.com/cloudevents/sdk-go/issues/525

**Closed by n3wscott** 2020-06-22 16:41 UTC

**Comment by mantzas** [comment] 2020-06-23 09:05
@n3wscott Hey, sorry for reopening this but it seems to be still broken. Any ETA on a release?

**Comment by n3wscott** [comment] 2020-06-23 11:34
Yes we need to cut a bugfix release. I can try that this week to remove this problem from the deps, we are pushing go mod a little here in a way it does not really want to be used. So the issue I linked is the tracking task to write the automation to help fix future releases.
