### ISSUE TITLE
[v0.3] Support batch json content type

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/sdk-go#63] opened 2019-03-07 01:05 UTC

**Comment by n3wscott** [comment] 2019-10-17 16:11
The current architecture of the SDK does not support implementing batch json because of how each request is assumed to have a response. 

this is changing in sdk v2. I am going to push this and we can fix it then.

**Comment by slinkydeveloper** [comment] 2020-03-20 09:08
Duplicate of #301

**Closed** 2020-03-20 09:08 UTC
Labels: SDKv2, duplicate, v1.0
