### ISSUE TITLE
Google Cloud Functions build error

### ISSUE THREAD

**Issue by playniuniu** [cloudevents/sdk-go#602] opened 2020-10-23 13:52 UTC
Hi 

I use google cloud functions go runtime, today I find it's always failed when build functions. 

The error log is:

Build failed: # github.com/cloudevents/sdk-go/v2/extensions
src/github.com/cloudevents/sdk-go/v2/extensions/distributed_tracing_extension.go:161:3: cannot use span (type trace.Span) as type *trace.Span in return argument:
*trace.Span is pointer to interface, not interface; Error ID: 1093f764

I have build with same code yesterday and it's passed and I not use this cloudevents in my code

So could you check what's the problem here?

Thanks

**Comment by slinkydeveloper** [comment] 2020-10-23 13:59
Duplicate of https://github.com/cloudevents/sdk-go/issues/601

**Closed by slinkydeveloper** 2020-10-23 13:59 UTC
